[package]
name = "mikoto"
version = "0.1.0"
edition = "2021"
default-run = "main"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "sub"
path = "src/sub.rs"

[dependencies]
http = "0.2.6"
hyper = "0.14"
lambda_http = "0.4.1"
lambda_runtime = "0.4.1"
serde = "1.0.133"
serde_json = "1.0"
tokio = "1.15.0"
