services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mikoto
      MYSQL_USER: mikoto
      MYSQL_PASSWORD: mikoto-pw
      MYSQL_ROOT_PASSWORD: my-root-pw
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass samplepw
