services:
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
      # management: http://localhost:15672
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
