service: mikoto-arm64

provider:
  name: aws

  runtime: provided.al2
  architecture: arm64

  memorySize: 128
  region: ap-northeast-1

package:
  individually: true

functions:
  main:
    handler: main
    package:
      artifact: ./artifacts/artifact_main.zip
  sub:
    handler: sub
    package:
      artifact: ./artifacts/artifact_sub.zip
