service: mikoto-fast

provider:
  name: aws
  runtime: provided.al2

  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}

  memorySize: 128
  architecture: arm64

  logRetentionInDays: 14
  versionFunctions: false

package:
  individually: true

functions:
  http:
    handler: main
    package:
      artifact: ./artifacts/artifact_main.zip
    events:
      - httpApi: "*"
  demo:
    handler: sub
    package:
      artifact: ./artifacts/artifact_sub.zip
  sub:
    handler: sub
    package:
      artifact: ./artifacts/artifact_sub.zip
