app = "mikoto-rabbitmq"

[build]
dockerfile = "Dockerfile"

# amqp(rabbitmq)
[[services]]
internal_port = 5672
protocol = "tcp"

[[services.ports]]
port = "47509"

# 5671: amqps
[[services.ports]]
handlers = ["tls"]
port = "5671"

[[services]]
internal_port = 15672
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"
