name: mikoto

on:
  pull_request:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@master
        with:
          name: mikoto-release
          path: target/release/hello

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - uses: actions/download-artifact@master
        with:
          name: mikoto-release
          path: target/release/hello
      - run: chmod +x target/release/*

      - name: deploy
        run: flyctl deploy --remote-only
